export const TENANT_PERMISSION_KEYS = {
  INVITATIONS_CREATE: "tenant:invitations:create",
  INVITATIONS_REVOKE: "tenant:invitations:revoke",
  SETTINGS_READ: "tenant:settings:read",
  SETTINGS_UPDATE: "tenant:settings:update",
  OWNERSHIP_TRANSFER: "tenant:ownership:transfer",
  AUDIT_READ: "tenant:audit:read",
  MODULE_INVENTORY_USE: "tenant:modules:inventory:use",
  MODULE_CRM_USE: "tenant:modules:crm:use",
  MODULE_HR_USE: "tenant:modules:hr:use",
  INVENTORY_READ: "tenant:inventory:read",
  INVENTORY_WRITE: "tenant:inventory:write",
  INVENTORY_DELETE: "tenant:inventory:delete",
  INVENTORY_STOCK: "tenant:inventory:stock",
  CRM_READ: "tenant:crm:read",
  CRM_WRITE: "tenant:crm:write",
  CRM_DELETE: "tenant:crm:delete",
  CRM_STAGE_UPDATE: "tenant:crm:stage:update",
  HR_EMPLOYEE_READ: "tenant:hr:employee:read",
  HR_EMPLOYEE_WRITE: "tenant:hr:employee:write",
  HR_EMPLOYEE_DELETE: "tenant:hr:employee:delete",
  HR_COMPENSATION_READ: "tenant:hr:compensation:read",
  HR_COMPENSATION_UPDATE: "tenant:hr:compensation:update",
} as const;

const OWNER_PERMISSIONS = new Set<string>([
  TENANT_PERMISSION_KEYS.INVITATIONS_CREATE,
  TENANT_PERMISSION_KEYS.INVITATIONS_REVOKE,
  TENANT_PERMISSION_KEYS.SETTINGS_READ,
  TENANT_PERMISSION_KEYS.SETTINGS_UPDATE,
  TENANT_PERMISSION_KEYS.OWNERSHIP_TRANSFER,
  TENANT_PERMISSION_KEYS.AUDIT_READ,
  TENANT_PERMISSION_KEYS.MODULE_INVENTORY_USE,
  TENANT_PERMISSION_KEYS.MODULE_CRM_USE,
  TENANT_PERMISSION_KEYS.MODULE_HR_USE,
  TENANT_PERMISSION_KEYS.INVENTORY_READ,
  TENANT_PERMISSION_KEYS.INVENTORY_WRITE,
  TENANT_PERMISSION_KEYS.INVENTORY_DELETE,
  TENANT_PERMISSION_KEYS.INVENTORY_STOCK,
  TENANT_PERMISSION_KEYS.CRM_READ,
  TENANT_PERMISSION_KEYS.CRM_WRITE,
  TENANT_PERMISSION_KEYS.CRM_DELETE,
  TENANT_PERMISSION_KEYS.CRM_STAGE_UPDATE,
  TENANT_PERMISSION_KEYS.HR_EMPLOYEE_READ,
  TENANT_PERMISSION_KEYS.HR_EMPLOYEE_WRITE,
  TENANT_PERMISSION_KEYS.HR_EMPLOYEE_DELETE,
  TENANT_PERMISSION_KEYS.HR_COMPENSATION_READ,
  TENANT_PERMISSION_KEYS.HR_COMPENSATION_UPDATE,
]);

const ADMIN_PERMISSIONS = new Set<string>([
  TENANT_PERMISSION_KEYS.SETTINGS_READ,
  TENANT_PERMISSION_KEYS.SETTINGS_UPDATE,
  TENANT_PERMISSION_KEYS.AUDIT_READ,
  TENANT_PERMISSION_KEYS.MODULE_INVENTORY_USE,
  TENANT_PERMISSION_KEYS.MODULE_CRM_USE,
  TENANT_PERMISSION_KEYS.MODULE_HR_USE,
  TENANT_PERMISSION_KEYS.INVENTORY_READ,
  TENANT_PERMISSION_KEYS.INVENTORY_WRITE,
  TENANT_PERMISSION_KEYS.INVENTORY_DELETE,
  TENANT_PERMISSION_KEYS.INVENTORY_STOCK,
  TENANT_PERMISSION_KEYS.CRM_READ,
  TENANT_PERMISSION_KEYS.CRM_WRITE,
  TENANT_PERMISSION_KEYS.CRM_DELETE,
  TENANT_PERMISSION_KEYS.CRM_STAGE_UPDATE,
  TENANT_PERMISSION_KEYS.HR_EMPLOYEE_READ,
  TENANT_PERMISSION_KEYS.HR_EMPLOYEE_WRITE,
  TENANT_PERMISSION_KEYS.HR_EMPLOYEE_DELETE,
  TENANT_PERMISSION_KEYS.HR_COMPENSATION_READ,
  TENANT_PERMISSION_KEYS.HR_COMPENSATION_UPDATE,
]);

const MEMBER_PERMISSIONS = new Set<string>([
  TENANT_PERMISSION_KEYS.SETTINGS_READ,
  TENANT_PERMISSION_KEYS.AUDIT_READ,
  TENANT_PERMISSION_KEYS.MODULE_INVENTORY_USE,
  TENANT_PERMISSION_KEYS.MODULE_CRM_USE,
  TENANT_PERMISSION_KEYS.MODULE_HR_USE,
  TENANT_PERMISSION_KEYS.INVENTORY_READ,
  TENANT_PERMISSION_KEYS.CRM_READ,
  TENANT_PERMISSION_KEYS.HR_EMPLOYEE_READ,
]);

function resolveRolePermissions(roleKey: string): Set<string> {
  switch (roleKey) {
    case "tenant:owner":
      return OWNER_PERMISSIONS;
    case "tenant:admin":
      return ADMIN_PERMISSIONS;
    case "tenant:member":
      return MEMBER_PERMISSIONS;
    default:
      return MEMBER_PERMISSIONS;
  }
}

export function hasTenantPermission(roleKey: string, permission: string): boolean {
  return resolveRolePermissions(roleKey).has(permission);
}

export function hasAllTenantPermissions(roleKey: string, permissions: readonly string[]): boolean {
  return permissions.every((permission) => hasTenantPermission(roleKey, permission));
}
